MCU = RP2040
BOOTLOADER = rp2040

OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes

WPM_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

#Sacado de rules.mk de Vial keymap
VIAL_ENABLE = yes
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

VIAL_INSECURE = yes